### ISSUE TITLE
why only the first question is crwalled

### ISSUE THREAD

**Issue by KunyiE1** [ericskh12/cityucs_acmoj_crawler#1]
I run the command but only first question is downloaded

**Comment by ericskh2** [comment]
Thank you for opening this issue, I will look into this soon.

**Comment by ericskh2** [comment]
> I run the command but only first question is downloaded

Hi @KunyiE1 , I updated some deprecated code. The latest version works for me on both Windows and macOS. 
Please give it a try and feel free to report any new issues.
Thanks again!

**Comment by ericskh2** [comment]
As no further reply has been received for two weeks, I assume the latest commit has fixed the issue. Therefore, I will close this issue.
